version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network
    environment:
      - BACKEND_URL=http://backend:5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - my_network
    container_name: backend

networks:
  my_network:
    driver: bridge