# Utiliza una imagen base de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del proyecto al directorio de trabajo
COPY . .

# Exponer el puerto que el backend utilizará (ajusta según sea necesario)
EXPOSE 5000

# Comando para ejecutar el backend
CMD ["npm", "run", "start:backend"]
