version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:5000"
    networks:
      - my_network

networks:
  my_network: